# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Venv_Projects/EducationMap/Package/app/designMap.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ME(object):
    def setupUi(self, ME):
        ME.setObjectName("ME")
        ME.resize(1900, 1025)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ME.sizePolicy().hasHeightForWidth())
        ME.setSizePolicy(sizePolicy)
        ME.setMinimumSize(QtCore.QSize(580, 750))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Users/Esat Can/Desktop/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ME.setWindowIcon(icon)
        ME.setAutoFillBackground(False)
        ME.setStyleSheet("")
        ME.setDocumentMode(True)
        self.centralwidget = QtWidgets.QWidget(ME)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("font-size:18px;\n"
"background-color: rgba(67, 99, 125, 255)")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(67, 99, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(67, 99, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(67, 99, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(67, 99, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(67, 99, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(67, 99, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(67, 99, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(67, 99, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(67, 99, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.tabWidget.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.tabWidget.setFont(font)
        self.tabWidget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.tabWidget.setAcceptDrops(False)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("border:none;font-size:25px; color:#fff")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabBarAutoHide(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_7)
        self.groupBox_3.setGeometry(QtCore.QRect(-730, 560, 401, 161))
        self.groupBox_3.setStyleSheet("color: rgb(255, 255, 255);border-radius: 8px;")
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.image_UAV_2 = QtWidgets.QLabel(self.groupBox_3)
        self.image_UAV_2.setGeometry(QtCore.QRect(20, 0, 81, 41))
        self.image_UAV_2.setStyleSheet("image: url(\'./img/gps.png\');")
        self.image_UAV_2.setText("")
        self.image_UAV_2.setObjectName("image_UAV_2")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_3)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(0, 50, 401, 111))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.enlem_lbl_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.enlem_lbl_2.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.enlem_lbl_2.setFont(font)
        self.enlem_lbl_2.setAutoFillBackground(False)
        self.enlem_lbl_2.setStyleSheet("color:white;background:none;;border:none;font-size:22px")
        self.enlem_lbl_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.enlem_lbl_2.setObjectName("enlem_lbl_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.enlem_lbl_2)
        self.veritext_Enlem = QtWidgets.QLabel(self.formLayoutWidget_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.veritext_Enlem.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.veritext_Enlem.setFont(font)
        self.veritext_Enlem.setAutoFillBackground(False)
        self.veritext_Enlem.setStyleSheet("color:white;background:none;;border:none;font-size:22px")
        self.veritext_Enlem.setAlignment(QtCore.Qt.AlignCenter)
        self.veritext_Enlem.setObjectName("veritext_Enlem")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.veritext_Enlem)
        self.enlem_lbl_5 = QtWidgets.QLabel(self.formLayoutWidget_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.enlem_lbl_5.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.enlem_lbl_5.setFont(font)
        self.enlem_lbl_5.setAutoFillBackground(False)
        self.enlem_lbl_5.setStyleSheet("color:white;background:none;;border:none;font-size:22px")
        self.enlem_lbl_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.enlem_lbl_5.setObjectName("enlem_lbl_5")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.enlem_lbl_5)
        self.veritext_Boylam = QtWidgets.QLabel(self.formLayoutWidget_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.veritext_Boylam.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.veritext_Boylam.setFont(font)
        self.veritext_Boylam.setAutoFillBackground(False)
        self.veritext_Boylam.setStyleSheet("color:white;background:none;;border:none;font-size:22px")
        self.veritext_Boylam.setAlignment(QtCore.Qt.AlignCenter)
        self.veritext_Boylam.setObjectName("veritext_Boylam")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.veritext_Boylam)
        self.enlem_lbl_9 = QtWidgets.QLabel(self.formLayoutWidget_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.enlem_lbl_9.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.enlem_lbl_9.setFont(font)
        self.enlem_lbl_9.setAutoFillBackground(False)
        self.enlem_lbl_9.setStyleSheet("color:white;background:none;;border:none;font-size:22px")
        self.enlem_lbl_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.enlem_lbl_9.setObjectName("enlem_lbl_9")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.enlem_lbl_9)
        self.veritext_Saat = QtWidgets.QLabel(self.formLayoutWidget_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.veritext_Saat.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.veritext_Saat.setFont(font)
        self.veritext_Saat.setAutoFillBackground(False)
        self.veritext_Saat.setStyleSheet("color:white;background:none;;border:none;font-size:22px")
        self.veritext_Saat.setAlignment(QtCore.Qt.AlignCenter)
        self.veritext_Saat.setObjectName("veritext_Saat")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.veritext_Saat)
        self.widget_4 = QtWidgets.QWidget(self.tab_7)
        self.widget_4.setGeometry(QtCore.QRect(10, 0, 1871, 971))
        self.widget_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.widget_4.setStyleSheet("background:  url(\'./img/bg.jpg\') no-repeat ;")
        self.widget_4.setObjectName("widget_4")
        self.label = QtWidgets.QLabel(self.widget_4)
        self.label.setGeometry(QtCore.QRect(-10, -10, 1881, 981))
        self.label.setStyleSheet("image: url(\'img/mapImage.png\');")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("img/mapImage.png"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.cbox_sehir = QtWidgets.QComboBox(self.widget_4)
        self.cbox_sehir.setGeometry(QtCore.QRect(510, 120, 851, 61))
        self.cbox_sehir.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.cbox_sehir.setAcceptDrops(False)
        self.cbox_sehir.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cbox_sehir.setStyleSheet("background: rgba(74,112,139,255);color:white;float:right;font-size:34px;border-radius: 15px;")
        self.cbox_sehir.setEditable(False)
        self.cbox_sehir.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.cbox_sehir.setModelColumn(0)
        self.cbox_sehir.setObjectName("cbox_sehir")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.cbox_sehir.addItem("")
        self.btn_Getir = QtWidgets.QPushButton(self.widget_4)
        self.btn_Getir.setGeometry(QtCore.QRect(1390, 120, 321, 61))
        self.btn_Getir.setStyleSheet("background-color:gray;border-radius: 22px;color:white;\n"
"")
        self.btn_Getir.setObjectName("btn_Getir")
        self.lbl_Edirne = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Edirne.setGeometry(QtCore.QRect(470, 280, 21, 91))
        self.lbl_Edirne.setText("")
        self.lbl_Edirne.setObjectName("lbl_Edirne")
        self.lbl_Kirklareli = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Kirklareli.setGeometry(QtCore.QRect(500, 270, 61, 51))
        self.lbl_Kirklareli.setText("")
        self.lbl_Kirklareli.setObjectName("lbl_Kirklareli")
        self.lbl_Tekirdag = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Tekirdag.setGeometry(QtCore.QRect(490, 320, 71, 31))
        self.lbl_Tekirdag.setText("")
        self.lbl_Tekirdag.setObjectName("lbl_Tekirdag")
        self.lbl_Tekirdag_2 = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Tekirdag_2.setGeometry(QtCore.QRect(570, 320, 75, 23))
        self.lbl_Tekirdag_2.setText("")
        self.lbl_Tekirdag_2.setObjectName("lbl_Tekirdag_2")
        self.lbl_Kocaeli = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Kocaeli.setGeometry(QtCore.QRect(640, 340, 31, 31))
        self.lbl_Kocaeli.setText("")
        self.lbl_Kocaeli.setObjectName("lbl_Kocaeli")
        self.lbl_Yalova = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Yalova.setGeometry(QtCore.QRect(590, 370, 41, 10))
        self.lbl_Yalova.setText("")
        self.lbl_Yalova.setObjectName("lbl_Yalova")
        self.lbl_Canakkale = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Canakkale.setGeometry(QtCore.QRect(450, 380, 75, 51))
        self.lbl_Canakkale.setText("")
        self.lbl_Canakkale.setObjectName("lbl_Canakkale")
        self.lbl_Balikesir = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Balikesir.setGeometry(QtCore.QRect(530, 400, 41, 61))
        self.lbl_Balikesir.setText("")
        self.lbl_Balikesir.setObjectName("lbl_Balikesir")
        self.lbl_Izmir = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Izmir.setGeometry(QtCore.QRect(480, 470, 41, 81))
        self.lbl_Izmir.setText("")
        self.lbl_Izmir.setObjectName("lbl_Izmir")
        self.lbl_Aydin = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Aydin.setGeometry(QtCore.QRect(510, 550, 75, 23))
        self.lbl_Aydin.setText("")
        self.lbl_Aydin.setObjectName("lbl_Aydin")
        self.lbl_Mugla = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Mugla.setGeometry(QtCore.QRect(520, 590, 81, 61))
        self.lbl_Mugla.setText("")
        self.lbl_Mugla.setObjectName("lbl_Mugla")
        self.lbl_Manisa = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Manisa.setGeometry(QtCore.QRect(520, 480, 81, 41))
        self.lbl_Manisa.setText("")
        self.lbl_Manisa.setObjectName("lbl_Manisa")
        self.lbl_Bursa = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Bursa.setGeometry(QtCore.QRect(570, 390, 75, 41))
        self.lbl_Bursa.setText("")
        self.lbl_Bursa.setObjectName("lbl_Bursa")
        self.lbl_Kutahya = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Kutahya.setGeometry(QtCore.QRect(600, 440, 75, 41))
        self.lbl_Kutahya.setText("")
        self.lbl_Kutahya.setObjectName("lbl_Kutahya")
        self.lbl_Usak = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Usak.setGeometry(QtCore.QRect(600, 500, 41, 31))
        self.lbl_Usak.setText("")
        self.lbl_Usak.setObjectName("lbl_Usak")
        self.lbl_Denizli = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Denizli.setGeometry(QtCore.QRect(590, 540, 51, 51))
        self.lbl_Denizli.setText("")
        self.lbl_Denizli.setObjectName("lbl_Denizli")
        self.lbl_Burdur = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Burdur.setGeometry(QtCore.QRect(630, 570, 61, 31))
        self.lbl_Burdur.setText("")
        self.lbl_Burdur.setObjectName("lbl_Burdur")
        self.lbl_Antalya = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Antalya.setGeometry(QtCore.QRect(650, 600, 131, 71))
        self.lbl_Antalya.setText("")
        self.lbl_Antalya.setObjectName("lbl_Antalya")
        self.lbl_Isparta = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Isparta.setGeometry(QtCore.QRect(680, 530, 61, 51))
        self.lbl_Isparta.setText("")
        self.lbl_Isparta.setObjectName("lbl_Isparta")
        self.lbl_Afyon = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Afyon.setGeometry(QtCore.QRect(660, 470, 75, 61))
        self.lbl_Afyon.setText("")
        self.lbl_Afyon.setObjectName("lbl_Afyon")
        self.lbl_Eskisehir = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Eskisehir.setGeometry(QtCore.QRect(680, 410, 61, 51))
        self.lbl_Eskisehir.setText("")
        self.lbl_Eskisehir.setObjectName("lbl_Eskisehir")
        self.lbl_Bilecik = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Bilecik.setGeometry(QtCore.QRect(640, 390, 51, 41))
        self.lbl_Bilecik.setText("")
        self.lbl_Bilecik.setObjectName("lbl_Bilecik")
        self.lbl_Sakarya = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Sakarya.setGeometry(QtCore.QRect(680, 342, 21, 31))
        self.lbl_Sakarya.setText("")
        self.lbl_Sakarya.setObjectName("lbl_Sakarya")
        self.lbl_Duzce = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Duzce.setGeometry(QtCore.QRect(700, 340, 41, 23))
        self.lbl_Duzce.setText("")
        self.lbl_Duzce.setObjectName("lbl_Duzce")
        self.lbl_Bolu = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Bolu.setGeometry(QtCore.QRect(710, 360, 75, 23))
        self.lbl_Bolu.setText("")
        self.lbl_Bolu.setObjectName("lbl_Bolu")
        self.lbl_Zonguldak = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Zonguldak.setGeometry(QtCore.QRect(730, 310, 41, 31))
        self.lbl_Zonguldak.setText("")
        self.lbl_Zonguldak.setObjectName("lbl_Zonguldak")
        self.lbl_Bartin = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Bartin.setGeometry(QtCore.QRect(770, 290, 31, 23))
        self.lbl_Bartin.setText("")
        self.lbl_Bartin.setObjectName("lbl_Bartin")
        self.lbl_Karabuk = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Karabuk.setGeometry(QtCore.QRect(780, 320, 41, 31))
        self.lbl_Karabuk.setText("")
        self.lbl_Karabuk.setObjectName("lbl_Karabuk")
        self.lbl_Ankara = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Ankara.setGeometry(QtCore.QRect(750, 390, 81, 81))
        self.lbl_Ankara.setText("")
        self.lbl_Ankara.setObjectName("lbl_Ankara")
        self.lbl_Konya = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Konya.setGeometry(QtCore.QRect(740, 480, 91, 111))
        self.lbl_Konya.setText("")
        self.lbl_Konya.setObjectName("lbl_Konya")
        self.lbl_Karaman = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Karaman.setGeometry(QtCore.QRect(800, 580, 61, 41))
        self.lbl_Karaman.setText("")
        self.lbl_Karaman.setObjectName("lbl_Karaman")
        self.lbl_Mersin = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Mersin.setGeometry(QtCore.QRect(820, 620, 91, 51))
        self.lbl_Mersin.setText("")
        self.lbl_Mersin.setObjectName("lbl_Mersin")
        self.lbl_Kastamonu = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Kastamonu.setGeometry(QtCore.QRect(810, 280, 81, 61))
        self.lbl_Kastamonu.setText("")
        self.lbl_Kastamonu.setObjectName("lbl_Kastamonu")
        self.lbl_Cankiri = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Cankiri.setGeometry(QtCore.QRect(810, 350, 51, 41))
        self.lbl_Cankiri.setText("")
        self.lbl_Cankiri.setObjectName("lbl_Cankiri")
        self.lbl_Kirikkale = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Kirikkale.setGeometry(QtCore.QRect(840, 400, 21, 51))
        self.lbl_Kirikkale.setText("")
        self.lbl_Kirikkale.setObjectName("lbl_Kirikkale")
        self.lbl_Kirsehir = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Kirsehir.setGeometry(QtCore.QRect(850, 440, 41, 41))
        self.lbl_Kirsehir.setText("")
        self.lbl_Kirsehir.setObjectName("lbl_Kirsehir")
        self.lbl_Aksaray = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Aksaray.setGeometry(QtCore.QRect(840, 490, 41, 51))
        self.lbl_Aksaray.setText("")
        self.lbl_Aksaray.setObjectName("lbl_Aksaray")
        self.lbl_Nigde = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Nigde.setGeometry(QtCore.QRect(880, 530, 41, 41))
        self.lbl_Nigde.setText("")
        self.lbl_Nigde.setObjectName("lbl_Nigde")
        self.lbl_Adana = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Adana.setGeometry(QtCore.QRect(910, 570, 61, 61))
        self.lbl_Adana.setText("")
        self.lbl_Adana.setObjectName("lbl_Adana")
        self.lbl_Hatay = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Hatay.setGeometry(QtCore.QRect(970, 620, 31, 61))
        self.lbl_Hatay.setText("")
        self.lbl_Hatay.setObjectName("lbl_Hatay")
        self.lbl_Corum = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Corum.setGeometry(QtCore.QRect(870, 340, 51, 61))
        self.lbl_Corum.setText("")
        self.lbl_Corum.setObjectName("lbl_Corum")
        self.lbl_Nevsehir = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Nevsehir.setGeometry(QtCore.QRect(880, 480, 41, 41))
        self.lbl_Nevsehir.setText("")
        self.lbl_Nevsehir.setObjectName("lbl_Nevsehir")
        self.lbl_Kayseri = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Kayseri.setGeometry(QtCore.QRect(930, 480, 71, 51))
        self.lbl_Kayseri.setText("")
        self.lbl_Kayseri.setObjectName("lbl_Kayseri")
        self.lbl_Yozgat = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Yozgat.setGeometry(QtCore.QRect(910, 410, 61, 51))
        self.lbl_Yozgat.setText("")
        self.lbl_Yozgat.setObjectName("lbl_Yozgat")
        self.lbl_Sinop = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Sinop.setGeometry(QtCore.QRect(880, 280, 61, 41))
        self.lbl_Sinop.setText("")
        self.lbl_Sinop.setObjectName("lbl_Sinop")
        self.lbl_Samsun = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Samsun.setGeometry(QtCore.QRect(930, 300, 91, 51))
        self.lbl_Samsun.setText("")
        self.lbl_Samsun.setObjectName("lbl_Samsun")
        self.lbl_Amasya = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Amasya.setGeometry(QtCore.QRect(920, 350, 75, 31))
        self.lbl_Amasya.setText("")
        self.lbl_Amasya.setObjectName("lbl_Amasya")
        self.lbl_Tokat = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Tokat.setGeometry(QtCore.QRect(980, 370, 61, 31))
        self.lbl_Tokat.setText("")
        self.lbl_Tokat.setObjectName("lbl_Tokat")
        self.lbl_Ordu = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Ordu.setGeometry(QtCore.QRect(1030, 340, 51, 41))
        self.lbl_Ordu.setText("")
        self.lbl_Ordu.setObjectName("lbl_Ordu")
        self.lbl_Sivas = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Sivas.setGeometry(QtCore.QRect(1010, 400, 81, 71))
        self.lbl_Sivas.setText("")
        self.lbl_Sivas.setObjectName("lbl_Sivas")
        self.lbl_Kahramanmaras = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Kahramanmaras.setGeometry(QtCore.QRect(1000, 520, 51, 61))
        self.lbl_Kahramanmaras.setText("")
        self.lbl_Kahramanmaras.setObjectName("lbl_Kahramanmaras")
        self.lbl_Osmaniye = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Osmaniye.setGeometry(QtCore.QRect(970, 590, 31, 23))
        self.lbl_Osmaniye.setText("")
        self.lbl_Osmaniye.setObjectName("lbl_Osmaniye")
        self.lbl_Kilis = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Kilis.setGeometry(QtCore.QRect(1010, 620, 31, 14))
        self.lbl_Kilis.setText("")
        self.lbl_Kilis.setObjectName("lbl_Kilis")
        self.lbl_Gaziantep = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Gaziantep.setGeometry(QtCore.QRect(1000, 592, 71, 31))
        self.lbl_Gaziantep.setText("")
        self.lbl_Gaziantep.setObjectName("lbl_Gaziantep")
        self.lbl_Sanliurfa = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Sanliurfa.setGeometry(QtCore.QRect(1090, 580, 81, 51))
        self.lbl_Sanliurfa.setText("")
        self.lbl_Sanliurfa.setObjectName("lbl_Sanliurfa")
        self.lbl_Malatya = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Malatya.setGeometry(QtCore.QRect(1050, 480, 51, 61))
        self.lbl_Malatya.setText("")
        self.lbl_Malatya.setObjectName("lbl_Malatya")
        self.lbl_Adiyaman = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Adiyaman.setGeometry(QtCore.QRect(1070, 550, 51, 23))
        self.lbl_Adiyaman.setText("")
        self.lbl_Adiyaman.setObjectName("lbl_Adiyaman")
        self.lbl_Erzincan = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Erzincan.setGeometry(QtCore.QRect(1100, 420, 101, 31))
        self.lbl_Erzincan.setText("")
        self.lbl_Erzincan.setObjectName("lbl_Erzincan")
        self.lbl_Giresun = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Giresun.setGeometry(QtCore.QRect(1080, 350, 41, 51))
        self.lbl_Giresun.setText("")
        self.lbl_Giresun.setObjectName("lbl_Giresun")
        self.lbl_Gumushane = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Gumushane.setGeometry(QtCore.QRect(1120, 370, 51, 41))
        self.lbl_Gumushane.setText("")
        self.lbl_Gumushane.setObjectName("lbl_Gumushane")
        self.lbl_Trabzon = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Trabzon.setGeometry(QtCore.QRect(1130, 350, 75, 23))
        self.lbl_Trabzon.setText("")
        self.lbl_Trabzon.setObjectName("lbl_Trabzon")
        self.lbl_Tunceli = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Tunceli.setGeometry(QtCore.QRect(1110, 450, 75, 41))
        self.lbl_Tunceli.setText("")
        self.lbl_Tunceli.setObjectName("lbl_Tunceli")
        self.lbl_Elazig = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Elazig.setGeometry(QtCore.QRect(1100, 490, 91, 31))
        self.lbl_Elazig.setText("")
        self.lbl_Elazig.setObjectName("lbl_Elazig")
        self.lbl_Diyarbakir = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Diyarbakir.setGeometry(QtCore.QRect(1160, 520, 81, 41))
        self.lbl_Diyarbakir.setText("")
        self.lbl_Diyarbakir.setObjectName("lbl_Diyarbakir")
        self.lbl_Mardin = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Mardin.setGeometry(QtCore.QRect(1180, 570, 91, 41))
        self.lbl_Mardin.setText("")
        self.lbl_Mardin.setObjectName("lbl_Mardin")
        self.lbl_Bayburt = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Bayburt.setGeometry(QtCore.QRect(1170, 380, 31, 23))
        self.lbl_Bayburt.setText("")
        self.lbl_Bayburt.setObjectName("lbl_Bayburt")
        self.lbl_Bingol = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Bingol.setGeometry(QtCore.QRect(1190, 450, 51, 51))
        self.lbl_Bingol.setText("")
        self.lbl_Bingol.setObjectName("lbl_Bingol")
        self.lbl_Rize = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Rize.setGeometry(QtCore.QRect(1200, 330, 51, 31))
        self.lbl_Rize.setText("")
        self.lbl_Rize.setObjectName("lbl_Rize")
        self.lbl_Artvin = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Artvin.setGeometry(QtCore.QRect(1250, 320, 51, 31))
        self.lbl_Artvin.setText("")
        self.lbl_Artvin.setObjectName("lbl_Artvin")
        self.lbl_Ardahan = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Ardahan.setGeometry(QtCore.QRect(1310, 310, 41, 41))
        self.lbl_Ardahan.setText("")
        self.lbl_Ardahan.setObjectName("lbl_Ardahan")
        self.lbl_Erzurum = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Erzurum.setGeometry(QtCore.QRect(1220, 370, 81, 81))
        self.lbl_Erzurum.setText("")
        self.lbl_Erzurum.setObjectName("lbl_Erzurum")
        self.lbl_Mus = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Mus.setGeometry(QtCore.QRect(1240, 470, 75, 23))
        self.lbl_Mus.setText("")
        self.lbl_Mus.setObjectName("lbl_Mus")
        self.lbl_Batman = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Batman.setGeometry(QtCore.QRect(1240, 520, 21, 51))
        self.lbl_Batman.setText("")
        self.lbl_Batman.setObjectName("lbl_Batman")
        self.lbl_Kars = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Kars.setGeometry(QtCore.QRect(1320, 350, 51, 61))
        self.lbl_Kars.setText("")
        self.lbl_Kars.setObjectName("lbl_Kars")
        self.lbl_Agri = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Agri.setGeometry(QtCore.QRect(1310, 430, 91, 31))
        self.lbl_Agri.setText("")
        self.lbl_Agri.setObjectName("lbl_Agri")
        self.lbl_Igdir = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Igdir.setGeometry(QtCore.QRect(1360, 410, 75, 23))
        self.lbl_Igdir.setText("")
        self.lbl_Igdir.setObjectName("lbl_Igdir")
        self.lbl_Bitlis = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Bitlis.setGeometry(QtCore.QRect(1280, 490, 41, 51))
        self.lbl_Bitlis.setText("")
        self.lbl_Bitlis.setObjectName("lbl_Bitlis")
        self.lbl_Van = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Van.setGeometry(QtCore.QRect(1340, 470, 51, 91))
        self.lbl_Van.setText("")
        self.lbl_Van.setObjectName("lbl_Van")
        self.lbl_Siirt = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Siirt.setGeometry(QtCore.QRect(1260, 540, 75, 23))
        self.lbl_Siirt.setText("")
        self.lbl_Siirt.setObjectName("lbl_Siirt")
        self.lbl_Sirnak = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Sirnak.setGeometry(QtCore.QRect(1280, 570, 75, 23))
        self.lbl_Sirnak.setText("")
        self.lbl_Sirnak.setObjectName("lbl_Sirnak")
        self.lbl_Hakkari = QtWidgets.QPushButton(self.widget_4)
        self.lbl_Hakkari.setGeometry(QtCore.QRect(1360, 570, 75, 31))
        self.lbl_Hakkari.setText("")
        self.lbl_Hakkari.setObjectName("lbl_Hakkari")
        self.frame_8 = QtWidgets.QFrame(self.widget_4)
        self.frame_8.setGeometry(QtCore.QRect(480, 700, 1061, 261))
        self.frame_8.setStyleSheet("background:rgb(255,255,255,90);border:none;border-radius: 15px;\n"
"")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_2 = QtWidgets.QLabel(self.frame_8)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 281, 71))
        self.label_2.setStyleSheet("font-size:20px;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.lbl_Mainokuryazar = QtWidgets.QLabel(self.frame_8)
        self.lbl_Mainokuryazar.setGeometry(QtCore.QRect(330, 100, 181, 71))
        self.lbl_Mainokuryazar.setStyleSheet("font-size:20px;")
        self.lbl_Mainokuryazar.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_Mainokuryazar.setObjectName("lbl_Mainokuryazar")
        self.label_4 = QtWidgets.QLabel(self.frame_8)
        self.label_4.setGeometry(QtCore.QRect(10, 180, 281, 71))
        self.label_4.setStyleSheet("font-size:20px;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_8)
        self.label_5.setGeometry(QtCore.QRect(520, 180, 281, 71))
        self.label_5.setStyleSheet("font-size:20px;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_8)
        self.label_6.setGeometry(QtCore.QRect(520, 100, 281, 71))
        self.label_6.setStyleSheet("font-size:20px;")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.lbl_Mainokuryazarolmayan = QtWidgets.QLabel(self.frame_8)
        self.lbl_Mainokuryazarolmayan.setGeometry(QtCore.QRect(330, 180, 181, 71))
        self.lbl_Mainokuryazarolmayan.setStyleSheet("font-size:20px;")
        self.lbl_Mainokuryazarolmayan.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_Mainokuryazarolmayan.setObjectName("lbl_Mainokuryazarolmayan")
        self.lbl_Mainokuryazaroran = QtWidgets.QLabel(self.frame_8)
        self.lbl_Mainokuryazaroran.setGeometry(QtCore.QRect(840, 100, 181, 71))
        self.lbl_Mainokuryazaroran.setStyleSheet("font-size:20px;")
        self.lbl_Mainokuryazaroran.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_Mainokuryazaroran.setObjectName("lbl_Mainokuryazaroran")
        self.lbl_Mainnufus = QtWidgets.QLabel(self.frame_8)
        self.lbl_Mainnufus.setGeometry(QtCore.QRect(840, 180, 181, 71))
        self.lbl_Mainnufus.setStyleSheet("font-size:20px;")
        self.lbl_Mainnufus.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_Mainnufus.setObjectName("lbl_Mainnufus")
        self.lbl_MainSehir = QtWidgets.QLabel(self.frame_8)
        self.lbl_MainSehir.setGeometry(QtCore.QRect(380, 10, 281, 71))
        self.lbl_MainSehir.setStyleSheet("font-size:20px;")
        self.lbl_MainSehir.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_MainSehir.setObjectName("lbl_MainSehir")
        self.label_3 = QtWidgets.QLabel(self.widget_4)
        self.label_3.setGeometry(QtCore.QRect(720, 20, 551, 61))
        self.label_3.setStyleSheet("font-size:60px;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.btn_HaritadaGoster = QtWidgets.QPushButton(self.widget_4)
        self.btn_HaritadaGoster.setGeometry(QtCore.QRect(150, 120, 321, 61))
        self.btn_HaritadaGoster.setStyleSheet("background-color:gray;border-radius: 22px;color:white;\n"
"")
        self.btn_HaritadaGoster.setObjectName("btn_HaritadaGoster")
        self.label_8 = QtWidgets.QLabel(self.widget_4)
        self.label_8.setGeometry(QtCore.QRect(30, 250, 51, 51))
        self.label_8.setStyleSheet("image: url(\'img/green.png\');")
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("img/green.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.widget_4)
        self.label_9.setGeometry(QtCore.QRect(30, 320, 51, 51))
        self.label_9.setStyleSheet("image: url(\'img/yellow.png\');")
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("img/yellow.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.widget_4)
        self.label_10.setGeometry(QtCore.QRect(30, 390, 51, 51))
        self.label_10.setStyleSheet("image: url(\'img/orange.png\');")
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("img/orange.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.widget_4)
        self.label_11.setGeometry(QtCore.QRect(90, 260, 121, 31))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.widget_4)
        self.label_12.setGeometry(QtCore.QRect(90, 330, 151, 31))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.widget_4)
        self.label_13.setGeometry(QtCore.QRect(90, 400, 121, 31))
        self.label_13.setObjectName("label_13")
        self.pbYuzde = QtWidgets.QProgressBar(self.widget_4)
        self.pbYuzde.setGeometry(QtCore.QRect(1690, 260, 101, 371))
        self.pbYuzde.setProperty("value", 100)
        self.pbYuzde.setAlignment(QtCore.Qt.AlignCenter)
        self.pbYuzde.setOrientation(QtCore.Qt.Vertical)
        self.pbYuzde.setObjectName("pbYuzde")
        self.label_14 = QtWidgets.QLabel(self.widget_4)
        self.label_14.setGeometry(QtCore.QRect(1610, 640, 241, 41))
        self.label_14.setObjectName("label_14")
        self.widget_4.raise_()
        self.groupBox_3.raise_()
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.frame_9 = QtWidgets.QFrame(self.tab_5)
        self.frame_9.setGeometry(QtCore.QRect(10, 10, 1861, 951))
        self.frame_9.setStyleSheet("background:rgb(255,255,255,90);border:none;border-radius: 15px;\n"
"")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.lbl_MainSehir_2 = QtWidgets.QLabel(self.frame_9)
        self.lbl_MainSehir_2.setGeometry(QtCore.QRect(550, 30, 691, 71))
        self.lbl_MainSehir_2.setStyleSheet("font-size:60px;")
        self.lbl_MainSehir_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_MainSehir_2.setObjectName("lbl_MainSehir_2")
        self.label_7 = QtWidgets.QLabel(self.frame_9)
        self.label_7.setGeometry(QtCore.QRect(240, 150, 1401, 701))
        self.label_7.setStyleSheet("font-size:30px;")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.tabWidget.addTab(self.tab_5, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        ME.setCentralWidget(self.centralwidget)
        self.actionExit = QtWidgets.QAction(ME)
        self.actionExit.setObjectName("actionExit")

        self.retranslateUi(ME)
        self.tabWidget.setCurrentIndex(0)
        self.cbox_sehir.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ME)

    def retranslateUi(self, ME):
        _translate = QtCore.QCoreApplication.translate
        ME.setWindowTitle(_translate("ME", "EDUCATION MAP"))
        self.groupBox_3.setTitle(_translate("ME", "GPS"))
        self.enlem_lbl_2.setText(_translate("ME", "ENLEM :"))
        self.veritext_Enlem.setText(_translate("ME", "88"))
        self.enlem_lbl_5.setText(_translate("ME", "BOYLAM:"))
        self.veritext_Boylam.setText(_translate("ME", "88"))
        self.enlem_lbl_9.setText(_translate("ME", "GPS SAATİ:"))
        self.veritext_Saat.setText(_translate("ME", "88"))
        self.cbox_sehir.setCurrentText(_translate("ME", "ADANA"))
        self.cbox_sehir.setItemText(0, _translate("ME", "ADANA"))
        self.cbox_sehir.setItemText(1, _translate("ME", "ADIYAMAN"))
        self.cbox_sehir.setItemText(2, _translate("ME", "AFYON"))
        self.cbox_sehir.setItemText(3, _translate("ME", "AĞRI"))
        self.cbox_sehir.setItemText(4, _translate("ME", "AMASYA"))
        self.cbox_sehir.setItemText(5, _translate("ME", "ANKARA"))
        self.cbox_sehir.setItemText(6, _translate("ME", "ANTALYA"))
        self.cbox_sehir.setItemText(7, _translate("ME", "ARTVİN"))
        self.cbox_sehir.setItemText(8, _translate("ME", "AYDIN"))
        self.cbox_sehir.setItemText(9, _translate("ME", "BALIKESİR"))
        self.cbox_sehir.setItemText(10, _translate("ME", "BİLECİK"))
        self.cbox_sehir.setItemText(11, _translate("ME", "BİNGÖL"))
        self.cbox_sehir.setItemText(12, _translate("ME", "BİTLİS"))
        self.cbox_sehir.setItemText(13, _translate("ME", "BOLU"))
        self.cbox_sehir.setItemText(14, _translate("ME", "BURDUR"))
        self.cbox_sehir.setItemText(15, _translate("ME", "BURSA"))
        self.cbox_sehir.setItemText(16, _translate("ME", "ÇANAKKALE"))
        self.cbox_sehir.setItemText(17, _translate("ME", "ÇANKIRI"))
        self.cbox_sehir.setItemText(18, _translate("ME", "ÇORUM"))
        self.cbox_sehir.setItemText(19, _translate("ME", "DENİZLİ"))
        self.cbox_sehir.setItemText(20, _translate("ME", "DİYARBAKIR"))
        self.cbox_sehir.setItemText(21, _translate("ME", "EDİRNE"))
        self.cbox_sehir.setItemText(22, _translate("ME", "ELAZIĞ"))
        self.cbox_sehir.setItemText(23, _translate("ME", "ERZİNCAN"))
        self.cbox_sehir.setItemText(24, _translate("ME", "ERZURUM"))
        self.cbox_sehir.setItemText(25, _translate("ME", "ESKİŞEHİR"))
        self.cbox_sehir.setItemText(26, _translate("ME", "GAZİANTEP"))
        self.cbox_sehir.setItemText(27, _translate("ME", "GİRESUN"))
        self.cbox_sehir.setItemText(28, _translate("ME", "GÜMÜŞHANE"))
        self.cbox_sehir.setItemText(29, _translate("ME", "HAKKARİ"))
        self.cbox_sehir.setItemText(30, _translate("ME", "HATAY"))
        self.cbox_sehir.setItemText(31, _translate("ME", "ISPARTA"))
        self.cbox_sehir.setItemText(32, _translate("ME", "MERSİN"))
        self.cbox_sehir.setItemText(33, _translate("ME", "İSTANBUL"))
        self.cbox_sehir.setItemText(34, _translate("ME", "İZMİR"))
        self.cbox_sehir.setItemText(35, _translate("ME", "KARS"))
        self.cbox_sehir.setItemText(36, _translate("ME", "KASTAMONU"))
        self.cbox_sehir.setItemText(37, _translate("ME", "KAYSERİ"))
        self.cbox_sehir.setItemText(38, _translate("ME", "KIRKLARELİ"))
        self.cbox_sehir.setItemText(39, _translate("ME", "KIRŞEHİR"))
        self.cbox_sehir.setItemText(40, _translate("ME", "KOCAELİ"))
        self.cbox_sehir.setItemText(41, _translate("ME", "KONYA"))
        self.cbox_sehir.setItemText(42, _translate("ME", "KÜTAHYA"))
        self.cbox_sehir.setItemText(43, _translate("ME", "MALATYA"))
        self.cbox_sehir.setItemText(44, _translate("ME", "MANİSA"))
        self.cbox_sehir.setItemText(45, _translate("ME", "KAHRAMANMARAŞ"))
        self.cbox_sehir.setItemText(46, _translate("ME", "MARDİN"))
        self.cbox_sehir.setItemText(47, _translate("ME", "MUĞLA"))
        self.cbox_sehir.setItemText(48, _translate("ME", "MUŞ"))
        self.cbox_sehir.setItemText(49, _translate("ME", "NEVŞEHİR"))
        self.cbox_sehir.setItemText(50, _translate("ME", "NİĞDE"))
        self.cbox_sehir.setItemText(51, _translate("ME", "ORDU"))
        self.cbox_sehir.setItemText(52, _translate("ME", "RİZE"))
        self.cbox_sehir.setItemText(53, _translate("ME", "SAKARYA"))
        self.cbox_sehir.setItemText(54, _translate("ME", "SAMSUN"))
        self.cbox_sehir.setItemText(55, _translate("ME", "SİVAS"))
        self.cbox_sehir.setItemText(56, _translate("ME", "SİİRT"))
        self.cbox_sehir.setItemText(57, _translate("ME", "SİNOP"))
        self.cbox_sehir.setItemText(58, _translate("ME", "TEKİRDAĞ"))
        self.cbox_sehir.setItemText(59, _translate("ME", "TOKAT"))
        self.cbox_sehir.setItemText(60, _translate("ME", "TRABZON"))
        self.cbox_sehir.setItemText(61, _translate("ME", "TUNCELİ"))
        self.cbox_sehir.setItemText(62, _translate("ME", "ŞANLIURFA"))
        self.cbox_sehir.setItemText(63, _translate("ME", "UŞAK"))
        self.cbox_sehir.setItemText(64, _translate("ME", "VAN"))
        self.cbox_sehir.setItemText(65, _translate("ME", "YOZGAT"))
        self.cbox_sehir.setItemText(66, _translate("ME", "ZONGULDAK"))
        self.cbox_sehir.setItemText(67, _translate("ME", "AKSARAY"))
        self.cbox_sehir.setItemText(68, _translate("ME", "BAYBURT"))
        self.cbox_sehir.setItemText(69, _translate("ME", "KARAMAN"))
        self.cbox_sehir.setItemText(70, _translate("ME", "KIRIKKALE"))
        self.cbox_sehir.setItemText(71, _translate("ME", "BATMAN"))
        self.cbox_sehir.setItemText(72, _translate("ME", "ŞIRNAK"))
        self.cbox_sehir.setItemText(73, _translate("ME", "BARTIN"))
        self.cbox_sehir.setItemText(74, _translate("ME", "ARDAHAN"))
        self.cbox_sehir.setItemText(75, _translate("ME", "IĞDIR"))
        self.cbox_sehir.setItemText(76, _translate("ME", "YALOVA"))
        self.cbox_sehir.setItemText(77, _translate("ME", "KARABÜK"))
        self.cbox_sehir.setItemText(78, _translate("ME", "KİLİS"))
        self.cbox_sehir.setItemText(79, _translate("ME", "OSMANİYE"))
        self.cbox_sehir.setItemText(80, _translate("ME", "DÜZCE"))
        self.btn_Getir.setToolTip(_translate("ME", "İstenilen Şehrin Özelliklerini Getirir"))
        self.btn_Getir.setText(_translate("ME", "SAYFADA GÖSTER"))
        self.label_2.setText(_translate("ME", "OKUR-YAZAR :"))
        self.lbl_Mainokuryazar.setText(_translate("ME", "000"))
        self.label_4.setText(_translate("ME", "OKUR-YAZAR DEĞİL:"))
        self.label_5.setText(_translate("ME", "NÜFUS:"))
        self.label_6.setText(_translate("ME", "OKUR-YAZAR ORANI:"))
        self.lbl_Mainokuryazarolmayan.setText(_translate("ME", "000"))
        self.lbl_Mainokuryazaroran.setText(_translate("ME", "000"))
        self.lbl_Mainnufus.setText(_translate("ME", "000"))
        self.lbl_MainSehir.setText(_translate("ME", "ŞEHİR"))
        self.label_3.setText(_translate("ME", "EDUCATION MAP"))
        self.btn_HaritadaGoster.setToolTip(_translate("ME", "İstenilen Şehrin Özelliklerini Getirir"))
        self.btn_HaritadaGoster.setText(_translate("ME", "GÖSTER"))
        self.label_11.setText(_translate("ME", "İLK 27 İL"))
        self.label_12.setText(_translate("ME", "İKİNCİ 27 İL"))
        self.label_13.setText(_translate("ME", "SON 27 İL"))
        self.label_14.setText(_translate("ME", "OKUR YAZAR ORANI"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("ME", "HARİTA"))
        self.lbl_MainSehir_2.setText(_translate("ME", "EDUACTION MAP"))
        self.label_7.setText(_translate("ME", "Bu yazılımda kullanılan bütün veriler Türkiye İstatistik Kurumundan mail talebi ile alınmıştır.\n"
" Harita renklendirmelerinde 81 il 3 bölüme ayrılmıştır. \n"
" Eğitim düzeyinin hesabı okuma yazma oranı ile bağdaşlaştırılarak ilk 27 ilk yeşil, \n"
" İkinci 27 il sarı ve son 27 ilk turuncu renkler ile belirtilmiştir."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("ME", "HAKKINDA"))
        self.actionExit.setText(_translate("ME", "Exit"))

